https://docs.snowflake.net/
https://docs.snowflake.net/manuals/user-guide.html

* Datawarehouse-as-service (Cloud)
Snowflake is a hybrid of traditional shared-disk database and shared-nothing database. Data is stored in shared-disk.  Query processing is MPP enabled with each node storing portion of data locally.  Simplicity of shard-disk with scale-out benefits of shared-nothing.

Standard Compliance: PCI DSS, HIPAA for PHI

BI & ETL Tools: Alooma, Attunity, Tableau, Talend, Stitch, Wherescape, Sigma Computing, Microstrategy, PowerBI, Looker, Informatica, Fivetran, Databricks

Regions Available, US, EU, APAC

Editions : Standard, Premier, Enterprise, Business Critical, VPS
Components:

** Database Storage
   compressed, columnar format optimized for  Datawarehousing access patterns.
** Query Processing
   virtual warehouses in various cloud providers(AWS, GCP, Azure). Each virtual warehouse is independent
** Cloud Services
   Infrastructure Manager, Optimizer, Metadata manager, Security, Authentication and access control.

* Data Lifecycle

** Organizing Datawarehousing
   CREATE DATABASE,
   CREATE SCHEMA
   CREATE TABLE
   CREATE TABLE AS SELECT

** Storing data
   INSERT INTO
   COPY INTO
   

** Querying data
   SELECT FROM
   WITH

** Update data
   UPDATE
   MERGE INTO
   DELETE FROM

** Remove data
   TRUNCATE TABLE
   DROP TABLE
   DROP SCHEMA
   DROP DATABASE

* Benchmarking
www.tpc.org/TPC_Documents_Current_Versions/pdf/TPC-DS_v2.5.0.pdf

TPCDS_SF100TCL: The 100 TB (scale factor 100,000) version represents 100 million customers and over 500,000 items stored, with sales data spanning 3 channels — stores, catalogs, and the web — covering a period of 5 years. The largest table, STORE_SALES, contains nearly 300 billion rows, and the fact tables contain over 560 billion rows in total.

TPCDS_SF10TCL: The 10 TB (scale factor 10,000) version represents 65 million customers and over 400,000 items stored, with sales data spanning 3 channels — stores, catalogs, and the web — covering a period of 5 years. The largest table, STORE_SALES, contains nearly 29 billion rows, and the fact tables contain over 56 billion rows in total

* Data Loading

** Bulk vs Continous
   Bulk through COPY
* Querying
  Correlation queries
  recursive CTEs for parts, management hierarchy etc variable depth. Can also be done with =CONNECT BY=.  But recursive CTEs are more powerful.
